print ("CV")
print ("Nume Prenume : Radetkaia Ecaterina")
print ("Data si locul nasterii: 07.06.2005, Balti")
print ("Domiciliu: Cartierul  Dacia , strada Alexandru cel bun 8/28")
print ("Studii: 2011-prezent IPLT ‘’M.E’’ ")
print ("Cunoasterea limbilor : Limba engleza  - nivelul B1 ,Limba germana - incepator ")
print ("Interese (sport, pictura) Practic boxul – 2ani      ")
print ("Caracteristici : Sociabila , curioasa  , optimista , responsabila,creativa  ")
print ("  Obiective profesionale : Universitatea de medicina  ")